desalting_params:
  basic_anions:
    - CHLORIDE
    - DIOXIDE
    - OXIDE
    - ACETATE
    - SULFATE
    - PHOSPHATE
    - HYDROXIDE
    - HYDROCHLORIDE
    - CITRATE
    - DIACETATE
    - TRIACETATE
    - ADIPATE
    - TARTRATE
    - BITARTRATE
    - FUMARATE
    - HEMIFUMARATE
    - MALEATE
    - BROMIDE
    - MEGLUMINE
    - BICARBONATE
    - MESYLATE
    - DISULFIDE
    - FLUORIDE
    - GLYCEROPHOSPHATE
    - GLUCEPTATE 
    
  basic_cations:
    - FERROUS
    - CALCIUM
    - SODIUM
    - MAGNESIUM
    - MANGANESE
    - POTASSIUM
    - ALUMINUM
    - TITANIUM
    - COPPER
    - CUPRIC
    - LYSINE
    - DISODIUM
  other_identifiers:
    - HYDRATE
    - MONOHYDRATE
    - DIHYDRATE
    - TRIHYDRATE
    - TETRAHYDRATE
    - HEPTAHYDRATE
    - ANHYDROUS
    - MONOBASIC
    - DIBASIC
    - LYSINE
    - ARGININE

name_resolver_params:
  url: https://name-resolution-sri.renci.org/
  service: lookup
  autocomplete_setting: false
  id_limit: 10
  offset: 0
  biolink_type: ChemicalOrDrugOrTreatment
  autocomplete: false

enrichment_tags:
  steroid:
    input_col: ID_Label
    output_col: is_steroid
    model_params: 
      model: gpt-4o-mini
      prompt: Is this drug a steroid drug? Return TRUE or FALSE only
      temperature: 0.8
  antibiotic:
    input_col: ID_Label
    output_col: is_antibiotic
    model_params:
      model: gpt-4o-mini
      prompt: Is this drug an antimicrobial drug such as an antibiotic, an antiviral, an antiparasitic, or an antifungal drug? Return TRUE or FALSE only
      temperature: 0.8
  chemotherapy:
    input_col: ID_Label
    output_col: is_chemotherapy
    model_params:
      model: gpt-4o-mini
      prompt: Is this drug a cytotoxic chemotherapy drug used to treat cancer? Return TRUE or FALSE only
      temperature: 0.8
  glucose_regulator:
    input_col: ID_Label
    output_col: is_glucose_regulator
    model_params:
      model: gpt-4o-mini
      prompt: Is this drug a drug which is primarily used to regulate glucose levels? Return TRUE or FALSE only
      temperature: 0.8

  