desalting_params:
  basic_anions:
    - CHLORIDE
    - DIOXIDE
    - OXIDE
    - ACETATE
    - SULFATE
    - PHOSPHATE
    - HYDROXIDE
    - HYDROCHLORIDE
    - CITRATE
    - DIACETATE
    - TRIACETATE
    - ADIPATE
    - TARTRATE
    - BITARTRATE
    - FUMARATE
    - HEMIFUMARATE
    - MALEATE
    - BROMIDE
    - MEGLUMINE
    - BICARBONATE
    - MESYLATE
    - DISULFIDE
    - FLUORIDE
    - GLYCEROPHOSPHATE
    - GLUCEPTATE
    - NITRITE
    - HYDROBROMIDE
    - SUCCINATE
    - TEREPHTHALATE
    - CARBONATE  
    - HYDROBROMIDE
    - BENZOATE 
    - BITARTRATE
    - FUROATE
    - PAMOATE
    - VALERATE
    - BESYLATE
    - TOSYLATE
    - METHYLSULFATE
    - SUCCINATE
    - LACTATE
    - DIPHOSPHATE
  basic_cations:
    - FERROUS
    - CALCIUM
    - SODIUM
    - MAGNESIUM
    - MANGANESE
    - POTASSIUM
    - ALUMINUM
    - TITANIUM
    - COPPER
    - CUPRIC
    - LYSINE
    - DISODIUM
    - ZINC
    - IODINE
  other_identifiers:
    - HYDRATE
    - MONOHYDRATE
    - DIHYDRATE
    - TRIHYDRATE
    - TETRAHYDRATE
    - HEPTAHYDRATE
    - ANHYDROUS
    - MONOBASIC
    - DIBASIC
    - LYSINE
    - ARGININE
    - POLISTIREX
    - COMPLEX
    - PRECIPITATED
    - DIMETHYL
    - ANHYDROUS
    - PENTAVALENT

# PURPLE BOOK
delimiters_purplebook:
  - " and "
  - ", with "
split_exclusions_purplebook:
  - ""
purplebook_drug_name_column: Proper Name
purplebook_approval_date_column: Approval Date

# INDIA
india_drug_name_column: Drug Name
india_approval_date_column: Date of Approval
delimiters_india:
  - " + "
  - " ; "
  - " and "
split_exclusions_india:
  - ""

# ORANGE BOOK
split_exclusions_orangebook:
  - LIOTRIX (T4;T3)
orangebook_drug_name_column: Ingredient
orangebook_approval_date_column: Approval_Date
delimiters_orangebook:
  - " AND "
  - " ; "
  - " W/ "
  - "; "

# EMA
delimiters_ema:
  - ", "
  - " / "
  - " AND "
ema_drug_name_column: International non-proprietary name (INN) / common name
ema_approval_date_column: Marketing authorisation date

split_exclusions_ema:
  - MENINGOCOCCAL GROUP B VACCINE (RECOMBINANT, ADSORBED)
  - PNEUMOCOCCAL POLYSACCHARIDE CONJUGATE VACCINE (13-VALENT, ADSORBED)
  - PNEUMOCOCCAL POLYSACCHARIDE CONJUGATE VACCINE (20-VALENT, ADSORBED)
  - COVID-19 VACCINE (RECOMBINANT, ADJUVANTED)
  - PANDEMIC INFLUENZA VACCINE (H5N1) (SURFACE ANTIGEN, INACTIVATED, ADJUVANTED)
  - DIPHTHERIA (D), TETANUS (T), PERTUSSIS (ACELLULAR, COMPONENT) (PA), HEPATITIS B (RDNA) (HBV), POLIOMYELITIS (INACTIVATED) (IPV) AND HAEMOPHILUS INFLUENZAE TYPE-B (HIB) CONJUGATE VACCINE (ADSORBED)
  - ZOONOTIC INFLUENZA VACCINE (H5N1) (SURFACE ANTIGEN, INACTIVATED, ADJUVANTED)
  - PANDEMIC INFLUENZA VACCINE (H5N1) (WHOLE VIRION, INACTIVATED, PREPARED IN CELL CULTURE)
  - COVID-19 VACCINE (RECOMBINANT, ADJUVANTED)
  - DENGUE TETRAVALENT VACCINE (LIVE, ATTENUATED)
  - EBOLA ZAIRE VACCINE (RVSV∆G-ZEBOV-GP, LIVE)
  - INFLUENZA VACCINE (LIVE ATTENUATED, NASAL)
  - INFLUENZA VACCINE (SURFACE ANTIGEN, INACTIVATED, PREPARED IN CELL CULTURES)
  - INFLUENZA VACCINE (SURFACE ANTIGEN, INACTIVATED, ADJUVANTED)
  - QUADRIVALENT INFLUENZA VACCINE (RECOMBINANT, PREPARED IN CELL CULTURE)
  - HUMAN PAPILLOMAVIRUS 9-VALENT VACCINE (RECOMBINANT, ADSORBED)
  - MENINGOCOCCAL GROUP B VACCINE (RDNA, COMPONENT, ADSORBED)
  - MENINGOCOCCAL GROUPS A, C, W-135 AND Y CONJUGATE VACCINE
  - MENINGOCOCCAL GROUP A, C, W-135 AND Y CONJUGATE VACCINE
  - DIPHTHERIA, TETANUS, PERTUSSIS (ACELLULAR, COMPONENT), HEPATITIS B (RDNA), POLIOMYELITIS (INACTIVATED) AND HAEMOPHILUS INFLUENZAE TYPE B CONJUGATE VACCINE (ADSORBED)
  - COVID-19 VACCINE (INACTIVATED, ADJUVANTED, ADSORBED)
  - EX VIVO EXPANDED AUTOLOGOUS HUMAN CORNEAL EPITHELIAL CELLS CONTAINING STEM CELLS
  - RESPIRATORY SYNCYTIAL VIRUS VACCINE (BIVALENT, RECOMBINANT)
  - ROTAVIRUS VACCINE, LIVE
  - IBANDRONIC ACID
  - INACTIVATED VACCINE AGAINST FOOT-AND-MOUTH DISEASE
  - RECOMBINANT RESPIRATORY SYNCYTIAL VIRUS PRE-FUSION F PROTEIN, ADJUVANTED WITH AS01E
  - JAPANESE ENCEPHALITIS VACCINE (INACTIVATED, ADSORBED)
  - HEPATITIS A (INACTIVATED) AND HEPATITIS B (RDNA) (HAB) VACCINE (ADSORBED)
  - HEPATITIS B (RDNA) VACCINE (ADJUVANTED, ADSORBED)
  - HEPATITIS A (INACTIVATED) AND HEPATITIS B (RDNA) (HAB) VACCINE (ADSORBED)
  - HUMAN PAPILLOMAVIRUS VACCINE [TYPES 16, 18] (RECOMBINANT, ADJUVANTED, ADSORBED)
  - SMALLPOX AND MONKEYPOX VACCINE (LIVE MODIFIED VACCINIA VIRUS ANKARA)
  - DIPHTHERIA, TETANUS, PERTUSSIS (ACELLULAR, COMPONENT), HEPATITIS B (RDNA), POLIOMYELITIS (INACTIVATED) AND HAEMOPHILUS TYPE B CONJUGATE VACCINE (ADSORBED)
  - HERPES ZOSTER VACCINE (RECOMBINANT, ADJUVANTED)
  - HUMAN PAPILLOMAVIRUS VACCINE [TYPES 6, 11, 16, 18] (RECOMBINANT, ADSORBED)
  - PANDEMIC INFLUENZA VACCINE (H5N1) (LIVE ATTENUATED, NASAL)
  - DEFATTED POWDER OF ARACHIS HYPOGAEA L., SEMEN (PEANUTS)
  - MEASLES, MUMPS, RUBELLA AND VARICELLA VACCINE (LIVE)
  - MEASLES, MUMPS AND RUBELLA VACCINE (LIVE)
  - PANDEMIC INFLUENZA VACCINE (H5N1) (SPLIT VIRION, INACTIVATED, ADJUVANTED)
  - HUMAN COAGULATION FACTOR VIII / HUMAN VON WILLEBRAND FACTOR
  - VACCINE AGAINST FELINE VIRAL RHINOTRACHEITIS, FELINE CALICIVIROSIS, FELINE PANLEUCOPENIA, FELINE LEUKEAMIA AND FELINE CHLAMYDOPHILA INFECTIONS
  - VACCINE AGAINST FELINE VIRAL RHINOTRACHEITIS, FELINE CALICIVIROSIS, FELINE PANLEUCOPENIA AND FELINE LEUKAEMIA
  - VACCINE AGAINST FELINE VIRAL RHINOTRACHEITIS, FELINE CALICIVIROSIS, FELINE PANLEUCOPENIA AND FELINE CHLAMYDOPHILA INFECTIONS
  - VACCINE AGAINST FELINE VIRAL RHINOTRACHEITIS, FELINE CALICIVIROSIS AND FELINE PANLEUCOPENIA
  - CHOLERA VACCINE, ORAL, LIVE
  - ANDEXANET ALFA
  - CHOLERA VACCINE (INACTIVATED, ORAL)
  - PANDEMIC INFLUENZA VACCINE (H5N1) (SPLIT VIRION, INACTIVATED, ADJUVANTED)
  - DIPHTHERIA (D), TETANUS (T), PERTUSSIS (ACELLULAR, COMPONENT) (PA), HEPATITIS B (RDNA) (HBV), POLIOMYELITIS (INACTIVATED) (IPV) AND HAEMOPHILUS INFLUENZAE TYPE-B (HIB) CONJUGATE VACCINE (ADSORBED)
  - INFLUENZA VACCINE (SURFACE ANTIGEN, INACTIVATED, PREPARED IN CELL CULTURES)
  - HERPES ZOSTER VACCINE (RECOMBINANT, ADJUVANTED)
  - DENGUE TETRAVALENT VACCINE (LIVE, ATTENUATED)
  - MENINGOCOCCAL GROUP B VACCINE (RDNA, COMPONENT, ADSORBED)
  - DIPHTHERIA, TETANUS, PERTUSSIS (ACELLULAR, COMPONENT), HEPATITIS B (RDNA), POLIOMYELITIS (INACTIVATED) AND HAEMOPHILUS TYPE B CONJUGATE VACCINE (ADSORBED)
  - RESPIRATORY SYNCYTIAL VIRUS VACCINE (BIVALENT, RECOMBINANT)
  - HUMAN PAPILLOMAVIRUS 9-VALENT VACCINE (RECOMBINANT, ADSORBED)
  - HEPATITIS A (INACTIVATED) AND HEPATITIS B (RDNA) (HAB) VACCINE (ADSORBED)
  - PANDEMIC INFLUENZA VACCINE (H5N1) (LIVE ATTENUATED, NASAL)
split_exclusions_ema_2:
  - HEPATITIS B (RDNA) VACCINE (ADJUVANTED, ADSORBED)
  - HUMAN PAPILLOMAVIRUS VACCINE [TYPES 16, 18] (RECOMBINANT, ADJUVANTED, ADSORBED)
  - DIPHTHERIA, TETANUS, PERTUSSIS (ACELLULAR, COMPONENT), HEPATITIS B (RDNA), POLIOMYELITIS (INACTIVATED) AND HAEMOPHILUS TYPE B CONJUGATE VACCINE (ADSORBED)
  - DIPHTHERIA (D), TETANUS (T), PERTUSSIS (ACELLULAR, COMPONENT) (PA), HEPATITIS B (RDNA) (HBV), POLIOMYELITIS (INACTIVATED) (IPV) AND HAEMOPHILUS INFLUENZAE TYPE-B (HIB) CONJUGATE VACCINE (ADSORBED)
  - DIPHTHERIA (D), TETANUS (T), PERTUSSIS (ACELLULAR, COMPONENT) (PA), HEPATITIS B (RDNA) (HBV), POLIOMYELITIS (INACTIVATED) (IPV) AND HAEMOPHILUS INFLUENZAE TYPE-B (HIB) CONJUGATE VACCINE (ADSORBED)
  - ROTAVIRUS VACCINE, LIVE
  - MENINGOCOCCAL GROUPS A, C, W-135 AND Y CONJUGATE VACCINE
  - INFLUENZA VACCINE (SURFACE ANTIGEN, INACTIVATED, PREPARED IN CELL CULTURES)
  - DIPHTHERIA (D), TETANUS (T), PERTUSSIS (ACELLULAR, COMPONENT) (PA), HEPATITIS B (RDNA) (HBV), POLIOMYELITIS (INACTIVATED) (IPV) AND HAEMOPHILUS INFLUENZAE TYPE-B (HIB) CONJUGATE VACCINE (ADSORBED)
  - HERPES ZOSTER VACCINE (RECOMBINANT, ADJUVANTED)
  - INFLUENZA VACCINE (SURFACE ANTIGEN, INACTIVATED, ADJUVANTED)
  - MENINGOCOCCAL GROUPS A, C, W-135 AND Y CONJUGATE VACCINE
  - RESPIRATORY SYNCYTIAL VIRUS VACCINE (BIVALENT, RECOMBINANT)
  - RESPIRATORY SYNCYTIAL VIRUS VACCINE (BIVALENT, RECOMBINANT)
  - HUMAN PAPILLOMAVIRUS VACCINE [TYPES 16, 18] (RECOMBINANT, ADJUVANTED, ADSORBED)
  - ZOONOTIC INFLUENZA VACCINE (H5N1) (SURFACE ANTIGEN, INACTIVATED, ADJUVANTED)
  - PANDEMIC INFLUENZA VACCINE (H5N1) (SURFACE ANTIGEN, INACTIVATED, ADJUVANTED)
  - PANDEMIC INFLUENZA VACCINE (H5N1) (LIVE ATTENUATED, NASAL)
  - RECOMBINANT RESPIRATORY SYNCYTIAL VIRUS PRE-FUSION F PROTEIN, ADJUVANTED WITH AS01E
  - HEPATITIS A (INACTIVATED) AND HEPATITIS B (RDNA) (HAB) VACCINE (ADSORBED)
  - INFLUENZA VACCINE (LIVE ATTENUATED, NASAL)
  - PNEUMOCOCCAL POLYSACCHARIDE CONJUGATE VACCINE (13-VALENT, ADSORBED)
  - MENINGOCOCCAL GROUP B VACCINE (RDNA, COMPONENT, ADSORBED)
  - MENINGOCOCCAL GROUPS A, C, W-135 AND Y CONJUGATE VACCINE
  - DIPHTHERIA, TETANUS, PERTUSSIS (ACELLULAR, COMPONENT), HEPATITIS B (RDNA), POLIOMYELITIS (INACTIVATED) AND HAEMOPHILUS INFLUENZAE TYPE B CONJUGATE VACCINE (ADSORBED)
  - PANDEMIC INFLUENZA VACCINE (H5N1) (SPLIT VIRION, INACTIVATED, ADJUVANTED)
  - JAPANESE ENCEPHALITIS VACCINE (INACTIVATED, ADSORBED)
  - INFLUENZA VACCINE (SURFACE ANTIGEN, INACTIVATED, ADJUVANTED)
  - HUMAN PAPILLOMAVIRUS 9-VALENT VACCINE (RECOMBINANT, ADSORBED)
  - PNEUMOCOCCAL POLYSACCHARIDE CONJUGATE VACCINE (20-VALENT, ADSORBED)
  - HUMAN PAPILLOMAVIRUS VACCINE [TYPES 6, 11, 16, 18] (RECOMBINANT, ADSORBED)
  - COVID-19 VACCINE (RECOMBINANT, ADJUVANTED)
  - QUADRIVALENT INFLUENZA VACCINE (RECOMBINANT, PREPARED IN CELL CULTURE)
  - MENINGOCOCCAL GROUP A, C, W-135 AND Y CONJUGATE VACCINE
  - DIPHTHERIA, TETANUS, PERTUSSIS (ACELLULAR, COMPONENT), HEPATITIS B (RDNA), POLIOMYELITIS (INACTIVATED) AND HAEMOPHILUS TYPE B CONJUGATE VACCINE (ADSORBED)
  - HERPES ZOSTER VACCINE (RECOMBINANT, ADJUVANTED)
  - INFLUENZA VACCINE (SURFACE ANTIGEN, INACTIVATED, PREPARED IN CELL CULTURES)
  - DIPHTHERIA (D), TETANUS (T), PERTUSSIS (ACELLULAR, COMPONENT) (PA), HEPATITIS B (RDNA) (HBV), POLIOMYELITIS (INACTIVATED) (IPV) AND HAEMOPHILUS INFLUENZAE TYPE-B (HIB) CONJUGATE VACCINE (ADSORBED)
  - PANDEMIC INFLUENZA VACCINE (H5N1) (SURFACE ANTIGEN, INACTIVATED, ADJUVANTED)
  - EBOLA VACCINE (MVA-BN-FILO [RECOMBINANT])
  - MENINGOCOCCAL GROUP B VACCINE (RDNA, COMPONENT, ADSORBED)
  - HEPATITIS B (RDNA) VACCINE (ADJUVANTED, ADSORBED)
  - HUMAN PAPILLOMAVIRUS VACCINE [TYPES 16, 18] (RECOMBINANT, ADJUVANTED, ADSORBED)
  - HEPATITIS A (INACTIVATED) AND HEPATITIS B (RDNA) (HAB) VACCINE (ADSORBED)
  - RECOMBINANT RESPIRATORY SYNCYTIAL VIRUS PRE-FUSION F PROTEIN, ADJUVANTED WITH AS01E
  - ZOONOTIC INFLUENZA VACCINE (H5N1) (SURFACE ANTIGEN, INACTIVATED, ADJUVANTED)
  - HUMAN PAPILLOMAVIRUS VACCINE [TYPES 6, 11, 16, 18] (RECOMBINANT, ADSORBED)
  - HEPATITIS B (RDNA) VACCINE (ADJUVANTED, ADSORBED)
  - JAPANESE ENCEPHALITIS VACCINE (INACTIVATED, ADSORBED)
  - DIPHTHERIA (D), TETANUS (T), PERTUSSIS (ACELLULAR, COMPONENT) (PA), HEPATITIS B (RDNA) (HBV), POLIOMYELITIS (INACTIVATED) (IPV) AND HAEMOPHILUS INFLUENZAE TYPE-B (HIB) CONJUGATE VACCINE (ADSORBED)
  - PANDEMIC INFLUENZA VACCINE (H5N1) (SURFACE ANTIGEN, INACTIVATED, ADJUVANTED)

exclusions_ema:
  - FLORBETABEN (18F)
  - PIFLUFOLASTAT (18F)
  - LUTETIUM (177LU) VIPIVOTIDE TETRAXETAN
  - SAMARIUM [153SM] LEXIDRONAM PENTASODIUM
  - IOFLUPANE (123I)
  - LUTETIUM (177LU) CHLORIDE
  - FLORBETAPIR (18F)
  - LUTETIUM (177LU) OXODOTREOTIDE
  - FLUCICLOVINE (18F)
  - IOFLUPANE (123L)
  - FLUTEMETAMOL (18F)
  - LUTETIUM (177 LU) CHLORIDE
  - 13C-UREA
  - SITAGLIPTIN, METFORMIN HYDROCHLORIDE
  - ""
  - NA
  - TECHNETIUM (99MTC) NOFETUMOMAB MERPENTAN
  - lutetium (177 Lu) chloride
  - fluciclovine (18F)
  - ioflupane (123l)
  - copper (64Cu) chloride
  - COPPER (64CU) CHLORIDE



# NAME RESOLVER
name_resolver_params:
  url: https://name-resolution-sri.renci.org/
  service: lookup
  autocomplete_setting: false
  id_limit: 10
  offset: 0
  biolink_type: ChemicalOrDrugOrTreatment
  autocomplete: false


# DRUG CATEGORY TAGS
enrichment_tags:
  steroid:
    input_col: ID_Label
    output_col: is_steroid
    model_params: 
      model: gpt-4o-mini
      prompt: Is this drug a corticosteroid drug? Return TRUE or FALSE only
      temperature: 0.8
  antibiotic:
    input_col: ID_Label
    output_col: is_antimicrobial
    model_params:
      model: gpt-4o
      prompt: "Are any of these drugs in any of the following drug classes: an antibiotic drug, an antiviral drug (usually end in '-vir' or '-udine'), an antiretroviral drug, an antiparasitic drug, or an antifungal drug? Return TRUE or FALSE only"
      temperature: 0.8
  chemotherapy:
    input_col: ID_Label
    output_col: is_chemotherapy
    model_params:
      model: gpt-4o-mini
      prompt: Is this drug a cytotoxic chemotherapy drug used to treat cancer? Return TRUE or FALSE only
      temperature: 0.8
  glucose_regulator:
    input_col: ID_Label
    output_col: is_glucose_regulator
    model_params:
      model: gpt-4o-mini
      prompt: Is this drug a drug which is primarily used to regulate glucose levels? Return TRUE or FALSE only
      temperature: 0.8

# APPROVAL TAGS
approval_tag_usa: "approved_usa"
approval_tag_europe: "approved_eu"
approval_tag_japan: "approved_japan"
approval_tag_india: "approved_india"