desalting_params:
  basic_anions:
    - CHLORIDE
    - DIOXIDE
    - OXIDE
    - ACETATE
    - SULFATE
    - PHOSPHATE
    - HYDROXIDE
    - HYDROCHLORIDE
    - CITRATE
    - DIACETATE
    - TRIACETATE
    - ADIPATE
    - TARTRATE
    - BITARTRATE
    - FUMARATE
    - HEMIFUMARATE
    - MALEATE
    - BROMIDE
    - MEGLUMINE
    - BICARBONATE
    - MESYLATE
    - DISULFIDE
    - FLUORIDE
    - GLYCEROPHOSPHATE
    - GLUCEPTATE
    - NITRITE
    - HYDROBROMIDE
    - SUCCINATE
    - TEREPHTHALATE
    - CARBONATE  
    - HYDROBROMIDE
    - BENZOATE 
    - BITARTRATE
    - FUROATE
    - PAMOATE
    - VALERATE
    - BESYLATE
    - TOSYLATE
    - METHYLSULFATE
    - SUCCINATE
    - LACTATE
    - DIPHOSPHATE

  basic_cations:
    - FERROUS
    - CALCIUM
    - SODIUM
    - MAGNESIUM
    - MANGANESE
    - POTASSIUM
    - ALUMINUM
    - TITANIUM
    - COPPER
    - CUPRIC
    - LYSINE
    - DISODIUM
    - ZINC
    - IODINE
  
  other_identifiers:
    - HYDRATE
    - MONOHYDRATE
    - DIHYDRATE
    - TRIHYDRATE
    - TETRAHYDRATE
    - HEPTAHYDRATE
    - ANHYDROUS
    - MONOBASIC
    - DIBASIC
    - LYSINE
    - ARGININE
    - POLISTIREX
    - COMPLEX
    - PRECIPITATED
    - DIMETHYL
    - ANHYDROUS
    - PENTAVALENT


# PURPLE BOOK
delimiters_purplebook:
  - " and "
  - ", with "

split_exclusions_purplebook:
  - ""


purplebook_drug_name_column: Proper Name
purplebook_approval_date_column: Approval Date

# INDIA
india_drug_name_column: Drug Name
india_approval_date_column: Date of Approval
delimiters_india:
  - " + "
  - " ; "
  - " and "
split_exclusions_india:
  - ""


# ORANGE BOOK
orangebook_drug_name_column: 
delimiters_orangebook:
  - " and "
  - " ; "

# NAME RESOLVER
name_resolver_params:
  url: https://name-resolution-sri.renci.org/
  service: lookup
  autocomplete_setting: false
  id_limit: 10
  offset: 0
  biolink_type: ChemicalOrDrugOrTreatment
  autocomplete: false


# DRUG CATEGORY TAGS
enrichment_tags:
  steroid:
    input_col: ID_Label
    output_col: is_steroid
    model_params: 
      model: gpt-4o-mini
      prompt: Is this drug a corticosteroid drug? Return TRUE or FALSE only
      temperature: 0.8
  antibiotic:
    input_col: ID_Label
    output_col: is_antimicrobial
    model_params:
      model: gpt-4o
      prompt: "Are any of these drugs in any of the following drug classes: an antibiotic drug, an antiviral drug (usually end in '-vir' or '-udine'), an antiretroviral drug, an antiparasitic drug, or an antifungal drug? Return TRUE or FALSE only"
      temperature: 0.8
  chemotherapy:
    input_col: ID_Label
    output_col: is_chemotherapy
    model_params:
      model: gpt-4o-mini
      prompt: Is this drug a cytotoxic chemotherapy drug used to treat cancer? Return TRUE or FALSE only
      temperature: 0.8
  glucose_regulator:
    input_col: ID_Label
    output_col: is_glucose_regulator
    model_params:
      model: gpt-4o-mini
      prompt: Is this drug a drug which is primarily used to regulate glucose levels? Return TRUE or FALSE only
      temperature: 0.8

# APPROVAL TAGS
 
approval_tag_usa: "approved_usa"
approval_tag_europe: "approved_eu"
approval_tag_japan: "approved_japan"
approval_tag_india: "approved_india"



  