repos:
  # Code formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        exclude: |
          (?x)^(
            pipelines/matrix/packages|
            pipelines/matrix/tests/|
            services/synonymizer/api/modules/synonymize
          )
      # Run the formatter.
      - id: ruff-format
        exclude: pipelines/matrix/packages
  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
    - id: isort
      args: [--treat-comment-as-code, "# %%", --float-to-top]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        exclude: | 
          (?x)^(
            pipelines/matrix/packages|services/|
            docs/src/experiments/ |
            services/synonymizer/api/modules/synonymize
          )
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
      - id: terraform_fmt
      # - id: terraform_docs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the ref you want to point at
    hooks:
    -   id: debug-statements
    -   id: check-merge-conflict
    # FUTURE: Enable for yaml checks
    # -   id: check-yaml

  # checks github actions files for errors
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint